server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: fastCloud-gateway
  profiles:
    active: @profiles.active@
  cloud:
    nacos:
      server-addr: @nacos.server@
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        group: @nacos.discovery.group@
        namespace: @nacos.namespace@
      config:
        group: @nacos.config.group@
        namespace: @nacos.namespace@
    config:
      import:
        - optional:nacos:application-common.yml
        - optional:nacos:@spring.application.name@.yml

